# The plugin uses bukkit-api 1.16.5, which means that the plugin *may* work on non-1.16.5 servers, but it is not guaranteed.
# Tested on Paper 1.16.5

# Speed of the camera (degrees/tick)
cameraSpeed: 1
# Animates the camera only when a player is in the camera
animateOnlyIfPlayers: true
# Delay in seconds before saving the room
saveDelay: 10
# Default language
lang: en_US

# Allow the player to sneak to leave the camera
allowSneakToLeave: true
# Allow the player to click to change the camera
allowClickToChange: true
# Allow the player to change the slot of the camera (left/right)
allowSlotToChange: true
# Allow the player to enter the camera via the screen
allowEnterByScreen: true
# Allow the player to enter the camera via the camera
allowEnterByCamera: false
# Admins can break the camera by hitting the camera (with confirmation)
adminClickToRemove: true
# Replace the components when the server starts
replaceOnReload: false
# Default limit of players in a room
defaultPlayerLimit: 10

camera:
  block:
    material: END_ROD

  # The cameraman is an armor stand holding the camera
  cameraman:
    inventory:
      helmet: # Rotate the camera
        material: PLAYER_HEAD
        headTextureBase64: ewogICJ0aW1lc3RhbXAiIDogMTY3MzcyMTc4NTg1NywKICAicHJvZmlsZUlkIiA6ICIyOTUzMzJiNjkwYWI0OTUzOTQzMzY0ZGE3ZTk4MjkzMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJzcGVjdGF0b3JfZGVhZCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84ZjM0NGNlYTRhYWI1Y2E0ZWI2ZjI3MGRmYTY2ZWFlOTg4M2RiNmNjY2M1ZmIyMTA2M2Q3NGY0NWVhNjliNmUzIgogICAgfQogIH0KfQ==
      chestplate:
      leggings:
      boots:
      mainHand:
      offHand:
    # Cameraman offset depending on the support direction
    # Offset 0,0,0 is the center of the support
    offset:
      NORTH: 0,-0.2,0.4
      SOUTH: 0,-0.2,-0.4
      EAST: -0.4,-0.2,0
      WEST: 0.4,-0.2,0
      DOWN: 0,0.0,0
      UP: 0,-0.7,0

  # The seat is an armor stand were the player sits
  seat:
    inventory:
      helmet:
      chestplate:
      leggings:
      boots:
      mainHand:
      offHand:
    # Seat offset (for the player)
    offset:
      NORTH: 0,0.9,0.4
      SOUTH: 0,0.9,-0.4
      EAST: -0.4,0.9,0
      WEST: 0.4,0.9,0
      DOWN: 0,1.2,0
      UP: 0,-0.8,0

  # The gamemode to use when the player is in the camera
  # Survival: The player can break blocks. (not recommanded)
  # Adventure: The player is hidden and is invulnerable. (recommanded)
  # Creative: The player have access to the creative inventory. (not recommanded)
  # Spectator: The player will see the invisible armor stand and can't use the allowSlotToChange. (recommanded)
  #   There is also a bug in Spectator where hitting the sneaking key too fast is not detected.
  gamemode: ADVENTURE


screen:
  materials:
    downSupport: PLAYER_HEAD
    upSupport: PLAYER_HEAD
    wallSupport: PLAYER_WALL_HEAD
    headTextureBase64: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzRhZDg4OTNiNDdkMDU5YzJlNGZmYmIwYTk3YjU1YTVjOWEwNTQxN2M5MDNjY2U1MTEyMjgxNjE0NmQ2MDc2MCJ9fX0=
